"""Variable catalog for the GUI's Statistik picker.

Provides a searchable, type-filterable list of variables the user can pick from
to build a live value list. Sources:

* the **full** SimConnect ``A:`` SimVars (with units + a "settable" flag) and
  ``K:`` key events, bundled as ``data/simconnect_catalog.json`` — generated by
  ``tools/gen_simconnect_catalog.py`` from Python-SimConnect (MIT),
* the JustFlight Arrow ``L:`` var list, parsed from ``docs/simvars-reference.md``
  at load time (no duplication of the 714 names).

Kept dependency-free and pure so it can be unit-tested without a display.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

# Variable "kind" tags, matching docs/simvars-reference.md §1.
KIND_SIMVAR = "A:"  # simulation variable (read, some writable)
KIND_EVENT = "K:"  # key event (write / trigger)
KIND_LVAR = "L:"  # add-on local var (read/write via WASM bridge)
KIND_VIRTUAL = "V:"  # user-defined virtual var (sim-independent, bridge-held)

KINDS = (KIND_SIMVAR, KIND_EVENT, KIND_LVAR, KIND_VIRTUAL)

# Bundled SimVar/Event catalog shipped inside the package (see module docstring).
_BUNDLED_CATALOG = Path(__file__).resolve().parent / "data" / "simconnect_catalog.json"


@dataclass(frozen=True)
class CatalogVar:
    """One selectable variable."""

    name: str
    kind: str  # one of KINDS
    unit: str  # "" when not applicable (events)
    category: str
    settable: bool = False  # A: only — whether the SimVar can be written

    @property
    def label(self) -> str:
        """Display label, e.g. ``A: AUTOPILOT ALTITUDE LOCK VAR  [Feet]``."""
        tail = f"  [{self.unit}]" if self.unit else ""
        return f"{self.kind} {self.name}{tail}"


def _load_sdk_catalog(path: Path) -> list[CatalogVar]:
    """Load the bundled ``A:`` SimVars and ``K:`` events (best-effort).

    On any error (missing file, format drift) return nothing rather than raise.
    """
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError, ValueError):
        return []
    out: list[CatalogVar] = []
    for v in data.get("simvars", []) if isinstance(data, dict) else []:
        if isinstance(v, dict) and isinstance(v.get("name"), str):
            out.append(CatalogVar(
                name=v["name"], kind=KIND_SIMVAR,
                unit=v.get("unit") or "", category=v.get("category") or "SimVar",
                settable=bool(v.get("settable", False)),
            ))
    for e in data.get("events", []) if isinstance(data, dict) else []:
        if isinstance(e, dict) and isinstance(e.get("name"), str):
            out.append(CatalogVar(
                name=e["name"], kind=KIND_EVENT, unit="",
                category=e.get("category") or "Event",
            ))
    return out


def _parse_lvars(reference_md: Path) -> list[CatalogVar]:
    """Pull the JF Arrow L:vars out of the ```text block in simvars-reference.md.

    The doc holds the enumerated 714 names under a fenced ``text`` block; we take
    the names between that fence and the next ``` line. Best-effort: on any error
    (missing file, format drift) we simply return nothing.
    """
    try:
        lines = reference_md.read_text(encoding="utf-8").splitlines()
    except OSError:
        return []
    out: list[CatalogVar] = []
    in_block = False
    for line in lines:
        name = line.strip()
        if not in_block:
            if name == "```text":  # the one fenced text block = the 714-name list
                in_block = True
            continue
        if name == "```":
            break
        # LVar names are bare identifiers (letters/digits/underscore), one per line.
        if name and all(c.isalnum() or c == "_" for c in name):
            out.append(
                CatalogVar(name=name, kind=KIND_LVAR, unit="number", category="JF Arrow LVar")
            )
    return out


def load_catalog(
    reference_md: Path | None = None, sdk_json: Path | None = None
) -> list[CatalogVar]:
    """Full catalog: bundled SDK A:/K: plus parsed JF L:vars (deduped, stable order)."""
    cat = _load_sdk_catalog(sdk_json or _BUNDLED_CATALOG)
    seen = {(v.kind, v.name) for v in cat}
    if reference_md is not None:
        for v in _parse_lvars(reference_md):
            if (v.kind, v.name) not in seen:
                cat.append(v)
                seen.add((v.kind, v.name))
    return cat


def local_var_catalog(local_vars) -> list[CatalogVar]:
    """Turn a profile's declared virtual vars into ``V:`` picker entries.

    ``local_vars`` is an iterable of :class:`~..models.LocalVar` (anything with
    ``name``/``unit``/``description``). They are settable (you write them like a
    SimVar). Merge the result into the base catalog whenever the profile changes,
    so a user's own variables appear in the picker alongside A:/K:/L:.
    """
    out: list[CatalogVar] = []
    for lv in local_vars:
        out.append(CatalogVar(
            name=lv.name,
            kind=KIND_VIRTUAL,
            unit=getattr(lv, "unit", "") or "",
            category=(getattr(lv, "description", "") or "Virtuelle Variable"),
            settable=True,
        ))
    return out


def filter_catalog(
    catalog: list[CatalogVar], *, kind: str | None = None, query: str = ""
) -> list[CatalogVar]:
    """Filter by ``kind`` (None = all) and a case-insensitive substring ``query``."""
    q = query.strip().lower()
    return [
        v
        for v in catalog
        if (kind is None or v.kind == kind) and (not q or q in v.name.lower())
    ]
